#!/bin/bash

if [ $# -eq 0 ]; then
	echo >&2 "Must provide name for project."
	exit 1
fi

mkdir -p $1/cmd

cat >$1/Makefile <<EOL
BIN_DIR := \${PWD}/bin
OS := linux
ARCH := amd64

# define deps
#   cd \${DEP_DIR}
#   git submodule init
#   git submodule update --remote
# endef

define gobuild
	cd cmd/; go mod tidy
	cd cmd/; GOOS=\${OS} GOARCH=\${ARCH} go build \$(1).go
	cd cmd/; mv \$(1) \${BIN_DIR}
endef

build:
	mkdir -p \${BIN_DIR}
	\$(call gobuild,main)

clean:
	rm -rf \${BIN_DIR}
EOL

cat >$1/cmd/main.go <<EOL
package main

import "fmt"

func main() {
	fmt.Println("Hello World!")
}
EOL

cd $1 && go mod init $1 && go mod tidy

echo "" >>go.mod
echo "replace helpers => ../helpers" >>go.mod
echo "require helpers v1.0.0" >>go.mod
